[build]
  command = "echo 'Build complete'"
  functions = "netlify/functions"
  publish = "."

[functions]
  external_node_modules = ["psycopg2-binary"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
