[build]
  command = "echo 'Build complete'"
  functions = "netlify/functions"
  publish = "."

[functions]
  # Python runtime for serverless functions
  runtime = "python3.9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/app"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.9"
