[build]
  command = "echo 'Build complete'"
  functions = "netlify/functions"
  publish = "."

[functions]
  # Netlify will auto-detect Python functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/app"
  status = 200
